CREATE TABLE `adt_b_interview_details` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `b_interview_details_rowid` int(3) NOT NULL,
  `first_visit` varchar(8) DEFAULT NULL,
  `fvy` int(2) DEFAULT NULL,
  `fvm` int(2) DEFAULT NULL,
  `fvd` int(2) DEFAULT NULL,
  `fvt` int(1) DEFAULT NULL,
  `fvr` int(1) DEFAULT NULL,
  `second_visit` varchar(8) DEFAULT NULL,
  `svy` int(2) DEFAULT NULL,
  `svm` int(2) DEFAULT NULL,
  `svd` int(2) DEFAULT NULL,
  `svt` int(1) DEFAULT NULL,
  `svr` int(1) DEFAULT NULL,
  `third_visit` varchar(8) DEFAULT NULL,
  `tvy` int(2) DEFAULT NULL,
  `tvm` int(2) DEFAULT NULL,
  `tvd` int(2) DEFAULT NULL,
  `tvt` int(1) DEFAULT NULL,
  `tvr` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`b_interview_details_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_closing_session` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `closing_session_rowid` int(3) NOT NULL,
  `q17_1` int(2) DEFAULT NULL,
  `q17_2` int(15) DEFAULT NULL,
  `barcode` varchar(7) DEFAULT NULL,
  `finalresp` int(1) DEFAULT NULL,
  `ending_time` varchar(8) DEFAULT NULL,
  `adult_close_session` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`closing_session_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_c_refusal_particulars` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `c_refusal_particulars_rowid` int(3) NOT NULL,
  `c_refp` int(1) DEFAULT NULL,
  `c_refp_oth` varchar(100) DEFAULT NULL,
  `c_reason` int(2) DEFAULT NULL,
  `c_reason_oth` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`c_refusal_particulars_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_fifteen_yrs_and_older_date` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `date_of_interview_15and_older` int(8) DEFAULT NULL,
  `starting_time` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_10_hiv_risk_perceptioo` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_10_hiv_risk_perceptioo_rowid` int(3) NOT NULL,
  `start_time_sect10_data_1` varchar(8) DEFAULT NULL,
  `q10_1` int(1) DEFAULT NULL,
  `q10_2a` int(1) DEFAULT NULL,
  `q10_2b` int(1) DEFAULT NULL,
  `q10_2c` int(1) DEFAULT NULL,
  `q10_2d` int(1) DEFAULT NULL,
  `q10_2e` int(1) DEFAULT NULL,
  `q10_2f` int(1) DEFAULT NULL,
  `q10_2g` int(1) DEFAULT NULL,
  `q10_2h` int(1) DEFAULT NULL,
  `q10_2i` int(1) DEFAULT NULL,
  `q10_2j` int(2) DEFAULT NULL,
  `q10_2k` int(2) DEFAULT NULL,
  `q10_2l` int(2) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_10_hiv_risk_perceptioo_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_10_hiv_risk_perceptiop` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_10_hiv_risk_perceptiop_rowid` int(3) NOT NULL,
  `q10_3a` int(1) DEFAULT NULL,
  `q10_3b` int(1) DEFAULT NULL,
  `q10_3c` int(1) DEFAULT NULL,
  `q10_3d` int(1) DEFAULT NULL,
  `q10_3e` int(1) DEFAULT NULL,
  `q10_3f` int(1) DEFAULT NULL,
  `q10_3g` int(1) DEFAULT NULL,
  `q10_3h` int(1) DEFAULT NULL,
  `q10_3i` int(1) DEFAULT NULL,
  `q10_3j` int(2) DEFAULT NULL,
  `q10_3k` int(2) DEFAULT NULL,
  `q10_4` int(1) DEFAULT NULL,
  `q10_5` int(1) DEFAULT NULL,
  `q10_6` int(1) DEFAULT NULL,
  `end_time_sect10_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_10_hiv_risk_perceptiop_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_11_alcohol_use` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_11_alcohol_use_rowid` int(3) NOT NULL,
  `start_time_sect11_data_1` varchar(8) DEFAULT NULL,
  `q11_1` int(1) DEFAULT NULL,
  `q11_2` int(1) DEFAULT NULL,
  `q11_3` int(1) DEFAULT NULL,
  `q11_4a` int(1) DEFAULT NULL,
  `q11_4b` int(1) DEFAULT NULL,
  `q11_4c` int(1) DEFAULT NULL,
  `q11_4d` int(1) DEFAULT NULL,
  `q11_4e` int(1) DEFAULT NULL,
  `q11_4f` int(1) DEFAULT NULL,
  `q11_5` int(1) DEFAULT NULL,
  `q11_6` int(1) DEFAULT NULL,
  `q11_7` int(1) DEFAULT NULL,
  `end_time_sect11_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_11_alcohol_use_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_12_use_of_other_substan` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_12_use_of_other_substan_rowid` int(3) NOT NULL,
  `start_time_sect12_data_1` varchar(8) DEFAULT NULL,
  `q12_1a` int(1) DEFAULT NULL,
  `q12_1b` int(1) DEFAULT NULL,
  `q12_1c` int(1) DEFAULT NULL,
  `q12_1d` int(1) DEFAULT NULL,
  `q12_1e` int(1) DEFAULT NULL,
  `q12_1f` int(1) DEFAULT NULL,
  `q12_1g` int(1) DEFAULT NULL,
  `q12_1h` int(1) DEFAULT NULL,
  `q12_1i` int(1) DEFAULT NULL,
  `q12_2` int(1) DEFAULT NULL,
  `q12_3` int(1) DEFAULT NULL,
  `end_time_sect12_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_12_use_of_other_substan_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_13_health_questions` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_13_health_questions_rowid` int(3) NOT NULL,
  `start_time_sect13_data_1` varchar(8) DEFAULT NULL,
  `q13_1` int(1) DEFAULT NULL,
  `q13_2` int(1) DEFAULT NULL,
  `q13_3` int(1) DEFAULT NULL,
  `q13_4` int(1) DEFAULT NULL,
  `q13_5` int(2) DEFAULT NULL,
  `q13_6` int(3) DEFAULT NULL,
  `q13_7a_i` int(1) DEFAULT NULL,
  `q13_7a_ii` int(1) DEFAULT NULL,
  `q13_7b_i` int(1) DEFAULT NULL,
  `q13_7b_ii` int(1) DEFAULT NULL,
  `q13_7c_i` int(1) DEFAULT NULL,
  `q13_7c_ii` int(1) DEFAULT NULL,
  `q13_7d_i` int(1) DEFAULT NULL,
  `q13_7d_ii` int(1) DEFAULT NULL,
  `q13_7e_i` int(1) DEFAULT NULL,
  `q13_7e_ii` int(1) DEFAULT NULL,
  `q13_7f_i` int(1) DEFAULT NULL,
  `q13_7f_ii` int(1) DEFAULT NULL,
  `q13_8` int(1) DEFAULT NULL,
  `q13_9` int(1) DEFAULT NULL,
  `end_time_sect13_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_13_health_questions_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_14_mental_health` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_14_mental_health_rowid` int(3) NOT NULL,
  `start_time_sect14_data_1` varchar(8) DEFAULT NULL,
  `q14_1` int(1) DEFAULT NULL,
  `q14_2` int(1) DEFAULT NULL,
  `q14_3` int(1) DEFAULT NULL,
  `q14_4` int(1) DEFAULT NULL,
  `q14_5` int(1) DEFAULT NULL,
  `q14_6` int(1) DEFAULT NULL,
  `q14_7` int(1) DEFAULT NULL,
  `q14_8` int(1) DEFAULT NULL,
  `q14_9` int(1) DEFAULT NULL,
  `q14_10` int(1) DEFAULT NULL,
  `end_time_sect14_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_14_mental_health_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_15_household_relations` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_15_household_relations_rowid` int(3) NOT NULL,
  `start_time_sect15_data_1` varchar(8) DEFAULT NULL,
  `ipv_selection` int(1) DEFAULT NULL,
  `q15_0` int(1) DEFAULT NULL,
  `q15_1a` int(1) DEFAULT NULL,
  `q15_1b` int(1) DEFAULT NULL,
  `q15_1c` int(1) DEFAULT NULL,
  `q15_1d` int(1) DEFAULT NULL,
  `q15_1e` int(1) DEFAULT NULL,
  `q15_1f` int(1) DEFAULT NULL,
  `q15_1g` int(1) DEFAULT NULL,
  `q15_1h` int(1) DEFAULT NULL,
  `q15_1i` int(1) DEFAULT NULL,
  `q15_1j` int(1) DEFAULT NULL,
  `q15_1k` int(1) DEFAULT NULL,
  `q15_2a` int(1) DEFAULT NULL,
  `q15_2b` int(1) DEFAULT NULL,
  `q15_2c` int(1) DEFAULT NULL,
  `q15_2d` int(1) DEFAULT NULL,
  `q15_3` int(1) DEFAULT NULL,
  `q15_4` int(1) DEFAULT NULL,
  `end_time_sect15_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_15_household_relations_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_16_migration` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_16_migration_rowid` int(3) NOT NULL,
  `start_time_sect16_data_1` varchar(8) DEFAULT NULL,
  `q16_1` int(2) DEFAULT NULL,
  `q16_2` int(1) DEFAULT NULL,
  `q16_3` int(1) DEFAULT NULL,
  `q16_4` int(2) DEFAULT NULL,
  `q16_5` int(2) DEFAULT NULL,
  `q16_6a` int(1) DEFAULT NULL,
  `q16_6b` int(1) DEFAULT NULL,
  `q16_7` int(1) DEFAULT NULL,
  `end_time_sect16_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_16_migration_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_1_respondent_s_biographi` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_1_respondent_s_biographi_rowid` int(3) NOT NULL,
  `start_time_sect_data_1` varchar(8) DEFAULT NULL,
  `kish_grid_respondent` int(1) DEFAULT NULL,
  `q1_1a` int(3) DEFAULT NULL,
  `q1_1_dob_year` int(4) DEFAULT NULL,
  `q1_1_dob_month` int(2) DEFAULT NULL,
  `q1_1_dob_day` int(2) DEFAULT NULL,
  `q1_2` int(1) DEFAULT NULL,
  `q1_3` int(1) DEFAULT NULL,
  `q1_4a` int(1) DEFAULT NULL,
  `q1_4b` int(2) DEFAULT NULL,
  `q1_4c` int(1) DEFAULT NULL,
  `q1_4d` int(1) DEFAULT NULL,
  `q1_4e` int(2) DEFAULT NULL,
  `q1_5a` int(1) DEFAULT NULL,
  `q1_5b` int(1) DEFAULT NULL,
  `q1_5c` int(2) DEFAULT NULL,
  `q1_6a` int(1) DEFAULT NULL,
  `q1_6b` int(1) DEFAULT NULL,
  `q1_6c` int(2) DEFAULT NULL,
  `q1_7` int(1) DEFAULT NULL,
  `q1_8` int(1) DEFAULT NULL,
  `q1_9` int(1) DEFAULT NULL,
  `q1_10` int(7) DEFAULT NULL,
  `q1_11` int(1) DEFAULT NULL,
  `q1_12` int(2) DEFAULT NULL,
  `q1_13a` int(1) DEFAULT NULL,
  `q1_13b` int(1) DEFAULT NULL,
  `q1_13c` int(1) DEFAULT NULL,
  `q1_13d` int(1) DEFAULT NULL,
  `q1_13e` int(1) DEFAULT NULL,
  `end_time_sect_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_1_respondent_s_biographi_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_1_respondent_s_biographj` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_1_respondent_s_biographj_rowid` int(3) NOT NULL,
  `start_time_sect_data_2` varchar(8) DEFAULT NULL,
  `q1_14` int(1) DEFAULT NULL,
  `q1_15a` int(1) DEFAULT NULL,
  `q1_15b` int(2) DEFAULT NULL,
  `q1_15c` int(2) DEFAULT NULL,
  `age_filter` int(1) DEFAULT NULL,
  `q1_16a` int(1) DEFAULT NULL,
  `q1_16b` int(1) DEFAULT NULL,
  `q1_16c` int(1) DEFAULT NULL,
  `q1_16d` int(1) DEFAULT NULL,
  `q1_16e` int(1) DEFAULT NULL,
  `q1_16f` int(1) DEFAULT NULL,
  `q1_16g` int(1) DEFAULT NULL,
  `q1_16h` int(1) DEFAULT NULL,
  `q1_16i` int(1) DEFAULT NULL,
  `q1_16j` int(2) DEFAULT NULL,
  `end_time_sect_data_2` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_1_respondent_s_biographj_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_1_respondent_s_biographk` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_1_respondent_s_biographk_rowid` int(3) NOT NULL,
  `start_time_sect_data_3` varchar(8) DEFAULT NULL,
  `q1_17a` int(1) DEFAULT NULL,
  `q1_17b` int(1) DEFAULT NULL,
  `q1_17c` int(1) DEFAULT NULL,
  `q1_17d` int(1) DEFAULT NULL,
  `q1_17e` int(1) DEFAULT NULL,
  `q1_17f` int(1) DEFAULT NULL,
  `q1_17g` int(1) DEFAULT NULL,
  `q1_17h` int(1) DEFAULT NULL,
  `q1_17i` int(1) DEFAULT NULL,
  `q1_17j` int(1) DEFAULT NULL,
  `q1_17k` int(1) DEFAULT NULL,
  `q1_17l` int(1) DEFAULT NULL,
  `end_time_sect_data_3` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_1_respondent_s_biographk_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_1_respondent_s_biographl` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_1_respondent_s_biographl_rowid` int(3) NOT NULL,
  `start_time_sect_data_4` varchar(8) DEFAULT NULL,
  `q1_18` int(1) DEFAULT NULL,
  `q1_19` int(2) DEFAULT NULL,
  `q1_20a` int(1) DEFAULT NULL,
  `q1_20b` int(1) DEFAULT NULL,
  `q1_20c` int(1) DEFAULT NULL,
  `q1_20d` int(1) DEFAULT NULL,
  `q1_20e` int(1) DEFAULT NULL,
  `q1_20f` int(1) DEFAULT NULL,
  `q1_20g` int(1) DEFAULT NULL,
  `q1_20h` int(1) DEFAULT NULL,
  `q1_20i` int(1) DEFAULT NULL,
  `q1_20j` int(2) DEFAULT NULL,
  `end_time_sect_data_4` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_1_respondent_s_biographl_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_2_knowledge_and_percept` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_2_knowledge_and_percept_rowid` int(3) NOT NULL,
  `start_time_sect2_data_2` varchar(8) DEFAULT NULL,
  `q2_1a` int(1) DEFAULT NULL,
  `q2_1b` int(1) DEFAULT NULL,
  `q2_1c` int(1) DEFAULT NULL,
  `q2_1d` int(1) DEFAULT NULL,
  `q2_1e` int(1) DEFAULT NULL,
  `q2_1f` int(1) DEFAULT NULL,
  `q2_1g` int(1) DEFAULT NULL,
  `q2_1h` int(1) DEFAULT NULL,
  `q2_1i` int(1) DEFAULT NULL,
  `q2_1j` int(2) DEFAULT NULL,
  `q2_1k` int(2) DEFAULT NULL,
  `q2_1l` int(2) DEFAULT NULL,
  `q2_1m` int(2) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_2_knowledge_and_percept_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_2_knowledge_and_percepu` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_2_knowledge_and_percepu_rowid` int(3) NOT NULL,
  `q2_5a` int(1) DEFAULT NULL,
  `q2_5b` int(1) DEFAULT NULL,
  `q2_5c` int(1) DEFAULT NULL,
  `q2_5d` int(1) DEFAULT NULL,
  `q2_5e` int(1) DEFAULT NULL,
  `q2_5f` int(1) DEFAULT NULL,
  `q2_5g` int(1) DEFAULT NULL,
  `q2_5h` int(1) DEFAULT NULL,
  `q2_5i` int(1) DEFAULT NULL,
  `q2_5j` int(1) DEFAULT NULL,
  `q2_6a` int(1) DEFAULT NULL,
  `q2_6b` int(1) DEFAULT NULL,
  `q2_6c` int(1) DEFAULT NULL,
  `q2_6d` int(1) DEFAULT NULL,
  `q2_6e` int(1) DEFAULT NULL,
  `q2_6f` int(1) DEFAULT NULL,
  `q2_6g` int(1) DEFAULT NULL,
  `q2_6h` int(1) DEFAULT NULL,
  `q2_7a` int(1) DEFAULT NULL,
  `q2_7b` int(1) DEFAULT NULL,
  `q2_7c` int(1) DEFAULT NULL,
  `q2_7d` int(1) DEFAULT NULL,
  `q2_7e` int(1) DEFAULT NULL,
  `q2_7f` int(1) DEFAULT NULL,
  `end_time_sect2_data_2` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_2_knowledge_and_percepu_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_2_knowledge_and_percepv` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_2_knowledge_and_percepv_rowid` int(3) NOT NULL,
  `q2_2a` int(1) DEFAULT NULL,
  `q2_2b` int(1) DEFAULT NULL,
  `q2_2c` int(1) DEFAULT NULL,
  `q2_2d` int(1) DEFAULT NULL,
  `q2_2e` int(1) DEFAULT NULL,
  `q2_2f` int(1) DEFAULT NULL,
  `q2_2g` int(1) DEFAULT NULL,
  `q2_2h` int(1) DEFAULT NULL,
  `q2_2i` int(1) DEFAULT NULL,
  `q2_3_1` int(1) DEFAULT NULL,
  `q2_3_2a` int(1) DEFAULT NULL,
  `q2_3_2b` int(1) DEFAULT NULL,
  `q2_3_2c` int(1) DEFAULT NULL,
  `q2_3_2d` int(1) DEFAULT NULL,
  `q2_3_2e` int(1) DEFAULT NULL,
  `q2_3_2f` int(1) DEFAULT NULL,
  `q2_3_2g` int(1) DEFAULT NULL,
  `q2_3_2h` int(1) DEFAULT NULL,
  `q2_3_2i` int(1) DEFAULT NULL,
  `q2_3_2j` int(2) DEFAULT NULL,
  `q2_3_2_other_specifz` varchar(100) DEFAULT NULL,
  `q2_4_1` int(1) DEFAULT NULL,
  `q2_4_2a` int(1) DEFAULT NULL,
  `q2_4_2b` int(1) DEFAULT NULL,
  `q2_4_2c` int(1) DEFAULT NULL,
  `q2_4_2d` int(1) DEFAULT NULL,
  `q2_4_2e` int(1) DEFAULT NULL,
  `q2_4_2f` int(1) DEFAULT NULL,
  `q2_4_2g` int(1) DEFAULT NULL,
  `q2_4_2h` int(1) DEFAULT NULL,
  `q2_4_2_other_specifz` varchar(100) DEFAULT NULL,
  `q2_4_3` int(1) DEFAULT NULL,
  `q2_4_3_other_specifz` varchar(60) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_2_knowledge_and_percepv_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_3_knowledge_attitudes` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_3_knowledge_attitudes_rowid` int(3) NOT NULL,
  `start_time_sect3_data_1` varchar(8) DEFAULT NULL,
  `q3_1a` int(1) DEFAULT NULL,
  `q3_1b` int(1) DEFAULT NULL,
  `q3_1c` int(1) DEFAULT NULL,
  `q3_2a` int(1) DEFAULT NULL,
  `q3_2b` int(1) DEFAULT NULL,
  `q3_2c` int(1) DEFAULT NULL,
  `q3_2d` int(1) DEFAULT NULL,
  `q3_2e` int(1) DEFAULT NULL,
  `q3_2f` int(1) DEFAULT NULL,
  `q3_3a` int(1) DEFAULT NULL,
  `q3_3b` int(1) DEFAULT NULL,
  `q3_3c` int(1) DEFAULT NULL,
  `q3_3d` int(1) DEFAULT NULL,
  `q3_3e` int(1) DEFAULT NULL,
  `q3_4` int(1) DEFAULT NULL,
  `q3_5` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_3_knowledge_attitudes_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_3_knowledge_attitudet` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_3_knowledge_attitudet_rowid` int(3) NOT NULL,
  `q3_6` int(1) DEFAULT NULL,
  `q3_7a` int(1) DEFAULT NULL,
  `q3_7b` int(1) DEFAULT NULL,
  `q3_7c` int(1) DEFAULT NULL,
  `q3_7d` int(1) DEFAULT NULL,
  `q3_7_other_specifz` varchar(60) DEFAULT NULL,
  `q3_8__month` int(2) DEFAULT NULL,
  `q3_8__year` int(4) DEFAULT NULL,
  `q3_9` int(1) DEFAULT NULL,
  `q3_10` int(1) DEFAULT NULL,
  `q3_11a` int(1) DEFAULT NULL,
  `q3_11b` int(1) DEFAULT NULL,
  `q3_11c` int(1) DEFAULT NULL,
  `q3_11d` int(1) DEFAULT NULL,
  `q3_12` int(1) DEFAULT NULL,
  `end_time_sect3_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_3_knowledge_attitudet_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_4_media_2` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_2_rowid` int(3) NOT NULL,
  `start_time_sect4media_data_1` varchar(8) DEFAULT NULL,
  `q4_21` int(1) DEFAULT NULL,
  `q4_22a` int(1) DEFAULT NULL,
  `q4_22b` int(1) DEFAULT NULL,
  `q4_22c` int(1) DEFAULT NULL,
  `q4_22d` int(1) DEFAULT NULL,
  `q4_22e` int(1) DEFAULT NULL,
  `q4_22f` int(1) DEFAULT NULL,
  `q4_22g` int(1) DEFAULT NULL,
  `q4_22h` int(1) DEFAULT NULL,
  `q4_22i` int(1) DEFAULT NULL,
  `q4_22j` int(2) DEFAULT NULL,
  `q4_22k` int(2) DEFAULT NULL,
  `q4_22l` int(2) DEFAULT NULL,
  `q4_22_other_specify` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_2_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_3` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_3_rowid` int(3) NOT NULL,
  `q4_41` int(1) DEFAULT NULL,
  `q4_42` int(1) DEFAULT NULL,
  `q4_43` int(1) DEFAULT NULL,
  `q4_44` int(1) DEFAULT NULL,
  `q4_45` int(1) DEFAULT NULL,
  `q4_46` int(1) DEFAULT NULL,
  `q4_47` int(1) DEFAULT NULL,
  `q4_48` int(1) DEFAULT NULL,
  `q4_49` int(1) DEFAULT NULL,
  `q4_50a` int(1) DEFAULT NULL,
  `q4_50b` int(1) DEFAULT NULL,
  `q4_50c` int(1) DEFAULT NULL,
  `q4_50d` int(1) DEFAULT NULL,
  `q4_50e` int(1) DEFAULT NULL,
  `q4_50f` int(1) DEFAULT NULL,
  `q4_50g` int(1) DEFAULT NULL,
  `q4_50h` int(1) DEFAULT NULL,
  `q4_50i` int(1) DEFAULT NULL,
  `q4_50j` int(1) DEFAULT NULL,
  `q4_50k` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_3_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_4_media_4` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_4_rowid` int(3) NOT NULL,
  `q4_61` int(1) DEFAULT NULL,
  `q4_62a` int(1) DEFAULT NULL,
  `q4_62b` int(1) DEFAULT NULL,
  `q4_62c` int(1) DEFAULT NULL,
  `q4_62d` int(1) DEFAULT NULL,
  `q4_62e` int(1) DEFAULT NULL,
  `q4_62f` int(1) DEFAULT NULL,
  `q4_62g` int(1) DEFAULT NULL,
  `q4_62h` int(1) DEFAULT NULL,
  `q4_62i` int(1) DEFAULT NULL,
  `q4_62j` int(2) DEFAULT NULL,
  `q4_62k` int(2) DEFAULT NULL,
  `q4_62l` int(2) DEFAULT NULL,
  `q4_62m` int(2) DEFAULT NULL,
  `q4_62n` int(2) DEFAULT NULL,
  `q4_62o` int(2) DEFAULT NULL,
  `q4_62_other_please_specify` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_4_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_a` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_a_rowid` int(3) NOT NULL,
  `q4_23a` int(1) DEFAULT NULL,
  `q4_23b` int(2) DEFAULT NULL,
  `q4_24a` int(1) DEFAULT NULL,
  `q4_24b` int(2) DEFAULT NULL,
  `q4_25` int(1) DEFAULT NULL,
  `q4_26` int(1) DEFAULT NULL,
  `q4_27` int(1) DEFAULT NULL,
  `q4_28` int(1) DEFAULT NULL,
  `q4_29` int(1) DEFAULT NULL,
  `q4_30` int(1) DEFAULT NULL,
  `q4_31` int(1) DEFAULT NULL,
  `q4_32a` int(1) DEFAULT NULL,
  `q4_32b` int(1) DEFAULT NULL,
  `q4_32c` int(1) DEFAULT NULL,
  `q4_32d` int(1) DEFAULT NULL,
  `q4_32e` int(1) DEFAULT NULL,
  `q4_32f` int(1) DEFAULT NULL,
  `q4_32g` int(1) DEFAULT NULL,
  `q4_32h` int(1) DEFAULT NULL,
  `q4_32i` int(1) DEFAULT NULL,
  `q4_32j` int(2) DEFAULT NULL,
  `q4_32_other_specifz` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_a_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_b` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_b_rowid` int(3) NOT NULL,
  `q4_33a` int(1) DEFAULT NULL,
  `q4_33b` int(1) DEFAULT NULL,
  `q4_33c` int(1) DEFAULT NULL,
  `q4_33d` int(1) DEFAULT NULL,
  `q4_33e` int(1) DEFAULT NULL,
  `q4_33f` int(1) DEFAULT NULL,
  `q4_33g` int(1) DEFAULT NULL,
  `q4_33h` int(1) DEFAULT NULL,
  `q4_34a` int(1) DEFAULT NULL,
  `q4_34b` int(1) DEFAULT NULL,
  `q4_34c` int(1) DEFAULT NULL,
  `q4_34d` int(1) DEFAULT NULL,
  `q4_34e` int(1) DEFAULT NULL,
  `q4_34f` int(1) DEFAULT NULL,
  `q4_34g` int(1) DEFAULT NULL,
  `q4_34g_other_specifza` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_b_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_c` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_c_rowid` int(3) NOT NULL,
  `q4_35` int(1) DEFAULT NULL,
  `q4_36` int(1) DEFAULT NULL,
  `q4_37` int(1) DEFAULT NULL,
  `q4_38` int(1) DEFAULT NULL,
  `q4_39` int(1) DEFAULT NULL,
  `q4_39a` int(1) DEFAULT NULL,
  `q4_40` int(1) DEFAULT NULL,
  `q4_40a` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_c_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_communication` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_communication_rowid` int(3) NOT NULL,
  `start_time_sect4norm_data_1` varchar(8) DEFAULT NULL,
  `q4_1a` int(1) DEFAULT NULL,
  `q4_1b` int(1) DEFAULT NULL,
  `q4_1c` int(1) DEFAULT NULL,
  `q4_1d` int(1) DEFAULT NULL,
  `q4_1e` int(1) DEFAULT NULL,
  `q4_1f` int(1) DEFAULT NULL,
  `q4_1g` int(1) DEFAULT NULL,
  `q4_1h` int(1) DEFAULT NULL,
  `q4_1i` int(1) DEFAULT NULL,
  `q4_1j` int(1) DEFAULT NULL,
  `q4_1k` int(1) DEFAULT NULL,
  `q4_1l` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_communication_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_communicatioo` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_communicatioo_rowid` int(3) NOT NULL,
  `q4_2` int(1) DEFAULT NULL,
  `q4_3` int(1) DEFAULT NULL,
  `q4_3_others_specifz` varchar(150) DEFAULT NULL,
  `q4_4a` int(1) DEFAULT NULL,
  `q4_4b` int(1) DEFAULT NULL,
  `q4_4c` int(1) DEFAULT NULL,
  `q4_4d` int(1) DEFAULT NULL,
  `q4_4e` int(1) DEFAULT NULL,
  `q4_4f` int(1) DEFAULT NULL,
  `q4_4g` int(1) DEFAULT NULL,
  `q4_4h` int(1) DEFAULT NULL,
  `q4_4i` int(1) DEFAULT NULL,
  `q4_4j` int(2) DEFAULT NULL,
  `q4_4k` int(2) DEFAULT NULL,
  `q4_4l` int(2) DEFAULT NULL,
  `q4_4m` int(2) DEFAULT NULL,
  `q4_4n` int(2) DEFAULT NULL,
  `q4_4_other_specifz` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_communicatioo_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_communicatiop` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_communicatiop_rowid` int(3) NOT NULL,
  `q4_11a` int(1) DEFAULT NULL,
  `q4_11b` int(1) DEFAULT NULL,
  `q4_11c` int(1) DEFAULT NULL,
  `q4_11d` int(1) DEFAULT NULL,
  `q4_11e` int(1) DEFAULT NULL,
  `q4_11f` int(1) DEFAULT NULL,
  `q4_11g` int(1) DEFAULT NULL,
  `q4_11h` int(1) DEFAULT NULL,
  `q4_11i` int(1) DEFAULT NULL,
  `q4_11j` int(2) DEFAULT NULL,
  `q4_11k` int(2) DEFAULT NULL,
  `q4_11l` int(2) DEFAULT NULL,
  `q4_11m` int(2) DEFAULT NULL,
  `q4_11n` int(2) DEFAULT NULL,
  `q4_11_other_specifza` varchar(100) DEFAULT NULL,
  `q4_12` int(1) DEFAULT NULL,
  `q4_13a` int(1) DEFAULT NULL,
  `q4_13b` int(1) DEFAULT NULL,
  `q4_13c` int(1) DEFAULT NULL,
  `q4_13d` int(1) DEFAULT NULL,
  `q4_13e` int(1) DEFAULT NULL,
  `q4_13f` int(1) DEFAULT NULL,
  `q4_13g` int(1) DEFAULT NULL,
  `q4_13_other_specifza` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_communicatiop_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_communicatioq` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_communicatioq_rowid` int(3) NOT NULL,
  `q4_14` int(1) DEFAULT NULL,
  `q4_15a` int(1) DEFAULT NULL,
  `q4_15b` int(1) DEFAULT NULL,
  `q4_15c` int(1) DEFAULT NULL,
  `q4_15d` int(1) DEFAULT NULL,
  `q4_15e` int(1) DEFAULT NULL,
  `q4_15f` int(1) DEFAULT NULL,
  `q4_15g` int(1) DEFAULT NULL,
  `q4_16a` int(1) DEFAULT NULL,
  `q4_16b` int(1) DEFAULT NULL,
  `q4_16c` int(1) DEFAULT NULL,
  `q4_16d` int(1) DEFAULT NULL,
  `q4_16e` int(1) DEFAULT NULL,
  `q4_16_other_specify` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_communicatioq_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_communicatior` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_communicatior_rowid` int(3) NOT NULL,
  `q4_17a` int(1) DEFAULT NULL,
  `q4_17b` int(1) DEFAULT NULL,
  `q4_17c` int(1) DEFAULT NULL,
  `q4_17d` int(1) DEFAULT NULL,
  `q4_17e` int(1) DEFAULT NULL,
  `q4_17f` int(1) DEFAULT NULL,
  `q4_17g` int(1) DEFAULT NULL,
  `q4_17_other_specifzc` varchar(100) DEFAULT NULL,
  `q4_18a` int(1) DEFAULT NULL,
  `q4_18b` int(1) DEFAULT NULL,
  `q4_18c` int(1) DEFAULT NULL,
  `q4_18d` int(1) DEFAULT NULL,
  `q4_18e` int(1) DEFAULT NULL,
  `q4_18f` int(1) DEFAULT NULL,
  `q4_18_other_specifzc` varchar(100) DEFAULT NULL,
  `q4_19` int(1) DEFAULT NULL,
  `q4_20` int(1) DEFAULT NULL,
  `end_time_sect4norm_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_communicatior_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_communicatios` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_communicatios_rowid` int(3) NOT NULL,
  `q4_5` int(1) DEFAULT NULL,
  `q4_6` int(1) DEFAULT NULL,
  `q4_6_other_specifza` varchar(70) DEFAULT NULL,
  `q4_7a` int(1) DEFAULT NULL,
  `q4_7b` int(1) DEFAULT NULL,
  `q4_7c` int(1) DEFAULT NULL,
  `q4_7d` int(1) DEFAULT NULL,
  `q4_7e` int(1) DEFAULT NULL,
  `q4_7f` int(1) DEFAULT NULL,
  `q4_7g` int(1) DEFAULT NULL,
  `q4_7h` int(1) DEFAULT NULL,
  `q4_7i` int(1) DEFAULT NULL,
  `q4_7j` int(2) DEFAULT NULL,
  `q4_7_other_specifza` varchar(70) DEFAULT NULL,
  `q4_8a` int(1) DEFAULT NULL,
  `q4_8b` int(1) DEFAULT NULL,
  `q4_8c` int(1) DEFAULT NULL,
  `q4_8d` int(1) DEFAULT NULL,
  `q4_8e` int(1) DEFAULT NULL,
  `q4_8_other_specifza` varchar(70) DEFAULT NULL,
  `q4_9` int(1) DEFAULT NULL,
  `q4_10` int(1) DEFAULT NULL,
  `q4_10_other_specifza` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_communicatios_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_4_media_d` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_d_rowid` int(3) NOT NULL,
  `q4_51` int(1) DEFAULT NULL,
  `q4_52` int(1) DEFAULT NULL,
  `q4_53` int(1) DEFAULT NULL,
  `q4_54` int(1) DEFAULT NULL,
  `q4_55` int(1) DEFAULT NULL,
  `q4_56` int(1) DEFAULT NULL,
  `q4_57a` int(1) DEFAULT NULL,
  `q4_57b` int(1) DEFAULT NULL,
  `q4_57c` int(1) DEFAULT NULL,
  `q4_57d` int(1) DEFAULT NULL,
  `q4_57e` int(1) DEFAULT NULL,
  `q4_57f` int(1) DEFAULT NULL,
  `q4_57g` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_d_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_e` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_e_rowid` int(3) NOT NULL,
  `q4_58` int(1) DEFAULT NULL,
  `q4_59a` int(1) DEFAULT NULL,
  `q4_59b` int(1) DEFAULT NULL,
  `q4_59c` int(1) DEFAULT NULL,
  `q4_59d` int(1) DEFAULT NULL,
  `q4_59e` int(1) DEFAULT NULL,
  `q4_59f` int(1) DEFAULT NULL,
  `q4_59g` int(1) DEFAULT NULL,
  `q4_59h` int(1) DEFAULT NULL,
  `q4_59i` int(1) DEFAULT NULL,
  `q4_59j` int(1) DEFAULT NULL,
  `q4_59k` int(1) DEFAULT NULL,
  `q4_59l` int(1) DEFAULT NULL,
  `q4_59_other_specifza` varchar(100) DEFAULT NULL,
  `q4_60` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_e_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_f` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_f_rowid` int(3) NOT NULL,
  `q4_70` int(1) DEFAULT NULL,
  `q4_71` int(1) DEFAULT NULL,
  `q4_72` int(1) DEFAULT NULL,
  `q4_73` int(1) DEFAULT NULL,
  `q4_74` int(1) DEFAULT NULL,
  `q4_75` int(1) DEFAULT NULL,
  `q4_76` int(1) DEFAULT NULL,
  `q4_77a` int(1) DEFAULT NULL,
  `q4_77b` int(1) DEFAULT NULL,
  `q4_77c` int(1) DEFAULT NULL,
  `q4_77d` int(1) DEFAULT NULL,
  `q4_77e` int(1) DEFAULT NULL,
  `q4_78` int(1) DEFAULT NULL,
  `q4_79a` int(1) DEFAULT NULL,
  `q4_79b` int(1) DEFAULT NULL,
  `q4_79c` int(1) DEFAULT NULL,
  `q4_79d` int(1) DEFAULT NULL,
  `q4_79e` int(1) DEFAULT NULL,
  `q4_79_other_specifz` varchar(100) DEFAULT NULL,
  `q4_80a` int(1) DEFAULT NULL,
  `q4_80b` int(1) DEFAULT NULL,
  `q4_80c` int(1) DEFAULT NULL,
  `q4_80d` int(1) DEFAULT NULL,
  `q4_80e` int(1) DEFAULT NULL,
  `q4_80f` int(1) DEFAULT NULL,
  `q4_80_other_specifz` varchar(100) DEFAULT NULL,
  `end_time_sect4media_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_f_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_g` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_g_rowid` int(3) NOT NULL,
  `q4_65a` int(1) DEFAULT NULL,
  `q4_65b` int(1) DEFAULT NULL,
  `q4_65c` int(1) DEFAULT NULL,
  `q4_65d` int(1) DEFAULT NULL,
  `q4_65e` int(1) DEFAULT NULL,
  `q4_65f` int(1) DEFAULT NULL,
  `q4_65g` int(1) DEFAULT NULL,
  `q4_65h` int(1) DEFAULT NULL,
  `q4_65i` int(1) DEFAULT NULL,
  `q4_65j` int(2) DEFAULT NULL,
  `q4_65k` int(2) DEFAULT NULL,
  `q4_65l` int(2) DEFAULT NULL,
  `q4_65_other_please_specifz` varchar(80) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_g_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_h` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_h_rowid` int(3) NOT NULL,
  `q4_69a` int(1) DEFAULT NULL,
  `q4_69b` int(1) DEFAULT NULL,
  `q4_69c` int(1) DEFAULT NULL,
  `q4_69d` int(1) DEFAULT NULL,
  `q4_69e` int(1) DEFAULT NULL,
  `q4_69f` int(1) DEFAULT NULL,
  `q4_69g` int(1) DEFAULT NULL,
  `q4_69h` int(1) DEFAULT NULL,
  `q4_69i` int(1) DEFAULT NULL,
  `q4_69j` int(2) DEFAULT NULL,
  `q4_69k` int(2) DEFAULT NULL,
  `q4_69l` int(2) DEFAULT NULL,
  `q4_69m` int(2) DEFAULT NULL,
  `q4_69n` int(2) DEFAULT NULL,
  `q4_69o` int(2) DEFAULT NULL,
  `q4_69_other_specifza` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_h_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_4_media_i` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_i_rowid` int(3) NOT NULL,
  `q4_66` int(1) DEFAULT NULL,
  `q4_67` int(1) DEFAULT NULL,
  `q4_68` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_i_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_4_media_j` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_4_media_j_rowid` int(3) NOT NULL,
  `q4_63` int(1) DEFAULT NULL,
  `q4_64a` int(1) DEFAULT NULL,
  `q4_64b` int(1) DEFAULT NULL,
  `q4_64c` int(1) DEFAULT NULL,
  `q4_64d` int(1) DEFAULT NULL,
  `q4_64e` int(1) DEFAULT NULL,
  `q4_64f` int(1) DEFAULT NULL,
  `q4_64g` int(1) DEFAULT NULL,
  `q4_64h` int(1) DEFAULT NULL,
  `q4_64i` int(1) DEFAULT NULL,
  `q4_64j` int(2) DEFAULT NULL,
  `q4_64k` int(2) DEFAULT NULL,
  `q4_64_other_please_specifz` varchar(80) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_4_media_j_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_5_sexual_history` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_5_sexual_history_rowid` int(3) NOT NULL,
  `start_time_sect5_data_1` varchar(8) DEFAULT NULL,
  `q5_1` int(1) DEFAULT NULL,
  `age_and_sex_filter` int(1) DEFAULT NULL,
  `q5_2a` int(1) DEFAULT NULL,
  `q5_2b` int(1) DEFAULT NULL,
  `q5_2c` int(1) DEFAULT NULL,
  `q5_2d` int(1) DEFAULT NULL,
  `q5_2e` int(1) DEFAULT NULL,
  `q5_2f` int(1) DEFAULT NULL,
  `q5_2g` int(1) DEFAULT NULL,
  `q5_2h` int(1) DEFAULT NULL,
  `q5_2i` int(1) DEFAULT NULL,
  `q5_2j` int(2) DEFAULT NULL,
  `q5_2_other_specify` varchar(100) DEFAULT NULL,
  `q5_3` int(2) DEFAULT NULL,
  `q5_4` int(2) DEFAULT NULL,
  `q5_5` int(1) DEFAULT NULL,
  `end_time_sect5_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_5_sexual_history_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_6_partner_1` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_6_partner_1_rowid` int(3) NOT NULL,
  `start_time_sect6_datap_1` varchar(8) DEFAULT NULL,
  `q6_9a_1` int(1) DEFAULT NULL,
  `q6_9b_1` int(1) DEFAULT NULL,
  `q6_9c_1` int(2) DEFAULT NULL,
  `q6_10a_1` int(2) DEFAULT NULL,
  `q6_10b_1` int(1) DEFAULT NULL,
  `q6_partner_1` int(2) DEFAULT NULL,
  `q6_10c_1` int(2) DEFAULT NULL,
  `q6_11_1` int(1) DEFAULT NULL,
  `q6_12_1` int(1) DEFAULT NULL,
  `q6_13_1` int(1) DEFAULT NULL,
  `q6_14_1_a_days_ago` int(2) DEFAULT NULL,
  `q6_14_1_b_month_ago` int(2) DEFAULT NULL,
  `q6_15_1a` int(1) DEFAULT NULL,
  `q6_15_1b` int(1) DEFAULT NULL,
  `q6_15_1c` int(1) DEFAULT NULL,
  `q6_16_1` int(1) DEFAULT NULL,
  `q6_17_1` int(1) DEFAULT NULL,
  `q6_18_1` int(2) DEFAULT NULL,
  `q6_19_1` int(1) DEFAULT NULL,
  `q6_20_1` int(1) DEFAULT NULL,
  `q6_21_1` int(1) DEFAULT NULL,
  `q6_22_1` int(1) DEFAULT NULL,
  `q6_23_1` int(1) DEFAULT NULL,
  `q6_24_1` int(1) DEFAULT NULL,
  `q6_25_1` int(1) DEFAULT NULL,
  `end_time_sect6_datap_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_6_partner_1_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_6_partner_s_2` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_6_partner_s_2_rowid` int(3) NOT NULL,
  `start_time_sect6_datap_2` varchar(8) DEFAULT NULL,
  `q6_9a_2` int(1) DEFAULT NULL,
  `q6_9b_2` int(1) DEFAULT NULL,
  `q6_9c_2` int(2) DEFAULT NULL,
  `q6_10a_2` int(2) DEFAULT NULL,
  `q6_10b_2` int(1) DEFAULT NULL,
  `q6_partner_2` int(2) DEFAULT NULL,
  `q6_10c_2` int(2) DEFAULT NULL,
  `q6_11_2` int(1) DEFAULT NULL,
  `q6_12_2` int(1) DEFAULT NULL,
  `q6_13_2` int(1) DEFAULT NULL,
  `q6_14_2_a_days_ago` int(2) DEFAULT NULL,
  `q6_14_2_b_month_ago` int(2) DEFAULT NULL,
  `q6_15_2a` int(1) DEFAULT NULL,
  `q6_15_2b` int(1) DEFAULT NULL,
  `q6_15_2c` int(1) DEFAULT NULL,
  `q6_16_2` int(1) DEFAULT NULL,
  `q6_17_2` int(1) DEFAULT NULL,
  `q6_18_2` int(2) DEFAULT NULL,
  `q6_19_2` int(1) DEFAULT NULL,
  `q6_20_2` int(1) DEFAULT NULL,
  `q6_21_2` int(1) DEFAULT NULL,
  `q6_22_2` int(1) DEFAULT NULL,
  `q6_23_2` int(1) DEFAULT NULL,
  `q6_24_2` int(1) DEFAULT NULL,
  `q6_25_2` int(1) DEFAULT NULL,
  `end_time_sect6_datap_2` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_6_partner_s_2_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `adt_section_6_partner_s_3` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_6_partner_s_3_rowid` int(3) NOT NULL,
  `start_time_sect6_datap_3` varchar(8) DEFAULT NULL,
  `q6_9a_3` int(1) DEFAULT NULL,
  `q6_9b_3` int(1) DEFAULT NULL,
  `q6_9c_3` int(2) DEFAULT NULL,
  `q6_10a_3` int(2) DEFAULT NULL,
  `q6_10b_3` int(1) DEFAULT NULL,
  `q6_partner_3` int(2) DEFAULT NULL,
  `q6_10c_3` int(2) DEFAULT NULL,
  `q6_11_3` int(1) DEFAULT NULL,
  `q6_12_3` int(1) DEFAULT NULL,
  `q6_13_3` int(1) DEFAULT NULL,
  `q6_14_3_a_days_ago` int(2) DEFAULT NULL,
  `q6_14_3_b_month_ago` int(2) DEFAULT NULL,
  `q6_15_3a` int(1) DEFAULT NULL,
  `q6_15_3b` int(1) DEFAULT NULL,
  `q6_15_3c` int(1) DEFAULT NULL,
  `q6_16_3` int(1) DEFAULT NULL,
  `q6_17_3` int(1) DEFAULT NULL,
  `q6_18_3` int(2) DEFAULT NULL,
  `q6_19_3` int(1) DEFAULT NULL,
  `q6_20_3` int(1) DEFAULT NULL,
  `q6_21_3` int(1) DEFAULT NULL,
  `q6_22_3` int(1) DEFAULT NULL,
  `q6_23_3` int(1) DEFAULT NULL,
  `q6_24_3` int(1) DEFAULT NULL,
  `q6_25_3` int(1) DEFAULT NULL,
  `end_time_sect6_datap_3` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_6_partner_s_3_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `adt_section_6_partner_s_and_part_1` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_6_partner_s_and_part_1_rowid` int(3) NOT NULL,
  `start_time_sect6_data_1` varchar(8) DEFAULT NULL,
  `q6_1` int(1) DEFAULT NULL,
  `q6_2` int(2) DEFAULT NULL,
  `q6_3` int(2) DEFAULT NULL,
  `q6_4` int(2) DEFAULT NULL,
  `q6_4_total` int(2) DEFAULT NULL,
  `q6_5` int(1) DEFAULT NULL,
  `q6_5a` int(1) DEFAULT NULL,
  `q6_5b` int(1) DEFAULT NULL,
  `q6_5c` int(1) DEFAULT NULL,
  `q6_5d` int(1) DEFAULT NULL,
  `q6_5e` int(1) DEFAULT NULL,
  `q6_5f` int(1) DEFAULT NULL,
  `q6_5g` int(1) DEFAULT NULL,
  `sexual_partners_filter` int(1) DEFAULT NULL,
  `q6_6` int(1) DEFAULT NULL,
  `q6_7` int(1) DEFAULT NULL,
  `q6_8a` int(2) DEFAULT NULL,
  `q6_8b` int(2) DEFAULT NULL,
  `q6_8c` int(1) DEFAULT NULL,
  `q6_8d` int(1) DEFAULT NULL,
  `q6_8e` int(1) DEFAULT NULL,
  `q6_8f` int(1) DEFAULT NULL,
  `q6_8g` int(1) DEFAULT NULL,
  `q6_8h` int(1) DEFAULT NULL,
  `q6_8i` int(1) DEFAULT NULL,
  `q6_8j` int(1) DEFAULT NULL,
  `end_time_sect6_data_a` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_6_partner_s_and_part_1_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_6_partner_s_and_part_3` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_6_partner_s_and_part_3_rowid` int(3) NOT NULL,
  `start_time_sect6_data_2` varchar(8) DEFAULT NULL,
  `q6_26` int(1) DEFAULT NULL,
  `non_condom_use_filter` int(1) DEFAULT NULL,
  `q6_27a` int(1) DEFAULT NULL,
  `q6_27b` int(1) DEFAULT NULL,
  `q6_27c` int(1) DEFAULT NULL,
  `q6_27d` int(1) DEFAULT NULL,
  `q6_27e` int(1) DEFAULT NULL,
  `q6_27f` int(1) DEFAULT NULL,
  `q6_27g` int(1) DEFAULT NULL,
  `q6_27h` int(1) DEFAULT NULL,
  `q6_27i` int(1) DEFAULT NULL,
  `q6_28` int(1) DEFAULT NULL,
  `end_time_sect6_data__2` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_6_partner_s_and_part_3_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_7_reproduction` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_7_reproduction_rowid` int(3) NOT NULL,
  `start_time_sect7_data_1` varchar(8) DEFAULT NULL,
  `sex_filter` int(1) DEFAULT NULL,
  `q7_1` int(1) DEFAULT NULL,
  `q7_2` int(1) DEFAULT NULL,
  `q7_3` int(1) DEFAULT NULL,
  `q7_4` int(2) DEFAULT NULL,
  `q7_5` int(1) DEFAULT NULL,
  `q7_6` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_7_reproduction_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `adt_section_7_reproductioo` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_7_reproductioo_rowid` int(3) NOT NULL,
  `q7_7a` int(1) DEFAULT NULL,
  `q7_7b` int(1) DEFAULT NULL,
  `q7_7c` int(1) DEFAULT NULL,
  `q7_7d` int(1) DEFAULT NULL,
  `q7_7e` int(1) DEFAULT NULL,
  `q7_7f` int(1) DEFAULT NULL,
  `q7_7g` int(1) DEFAULT NULL,
  `q7_7h` int(1) DEFAULT NULL,
  `q7_7i` int(1) DEFAULT NULL,
  `q7_7j` int(2) DEFAULT NULL,
  `q7_8a` int(1) DEFAULT NULL,
  `q7_8b` int(1) DEFAULT NULL,
  `q7_8c` int(1) DEFAULT NULL,
  `q7_8d` int(1) DEFAULT NULL,
  `q7_8e` int(1) DEFAULT NULL,
  `q7_8f` int(1) DEFAULT NULL,
  `q7_8g` int(1) DEFAULT NULL,
  `q7_8h` int(1) DEFAULT NULL,
  `q7_8i` int(1) DEFAULT NULL,
  `q7_8j` int(2) DEFAULT NULL,
  `q7_8k` int(2) DEFAULT NULL,
  `end_time_sect7_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_7_reproductioo_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_8_male_circumcision_1` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_8_male_circumcision_1_rowid` int(3) NOT NULL,
  `the_next_section_deals_with_circ` int(1) DEFAULT NULL,
  `start_time_sect8_data_1` varchar(8) DEFAULT NULL,
  `q8_1` int(1) DEFAULT NULL,
  `q8_2` int(1) DEFAULT NULL,
  `q8_3` int(2) DEFAULT NULL,
  `q8_4` int(1) DEFAULT NULL,
  `q8_5a` int(1) DEFAULT NULL,
  `q8_5b` int(1) DEFAULT NULL,
  `q8_5c` int(1) DEFAULT NULL,
  `q8_5d` int(1) DEFAULT NULL,
  `q8_5e` int(1) DEFAULT NULL,
  `q8_6` int(1) DEFAULT NULL,
  `q8_7` int(1) DEFAULT NULL,
  `q8_8` int(1) DEFAULT NULL,
  `q8_9` int(1) DEFAULT NULL,
  `q8_10` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_8_male_circumcision_1_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_8_male_circumcision_2` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_8_male_circumcision_2_rowid` int(3) NOT NULL,
  `q8_11` int(1) DEFAULT NULL,
  `q8_12` int(1) DEFAULT NULL,
  `q8_13` int(1) DEFAULT NULL,
  `q8_14` int(1) DEFAULT NULL,
  `q8_15` int(1) DEFAULT NULL,
  `q8_16a` int(1) DEFAULT NULL,
  `q8_16b` int(1) DEFAULT NULL,
  `q8_16c` int(1) DEFAULT NULL,
  `q8_16d` int(1) DEFAULT NULL,
  `q8_16e` int(1) DEFAULT NULL,
  `q8_16f` int(1) DEFAULT NULL,
  `q8_16g` int(1) DEFAULT NULL,
  `q8_16h` int(1) DEFAULT NULL,
  `q8_16i` int(1) DEFAULT NULL,
  `q8_17` int(1) DEFAULT NULL,
  `q8_17_other_specifz` varchar(100) DEFAULT NULL,
  `q8_18` int(1) DEFAULT NULL,
  `q8_19` int(1) DEFAULT NULL,
  `end_time_sect8_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_8_male_circumcision_2_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_9_hiv_counselling_and_u` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_9_hiv_counselling_and_u_rowid` int(3) NOT NULL,
  `q9_15a` int(1) DEFAULT NULL,
  `q9_15b` int(1) DEFAULT NULL,
  `q9_15c` int(1) DEFAULT NULL,
  `q9_15d` int(1) DEFAULT NULL,
  `q9_15e` int(1) DEFAULT NULL,
  `q9_15f` int(1) DEFAULT NULL,
  `q9_15g` int(1) DEFAULT NULL,
  `q9_15h` int(1) DEFAULT NULL,
  `q9_15_other_specifz` varchar(50) DEFAULT NULL,
  `q9_16_days` int(2) DEFAULT NULL,
  `q9_16_months` int(2) DEFAULT NULL,
  `q9_17a` int(2) DEFAULT NULL,
  `sexual_activity_filter` int(1) DEFAULT NULL,
  `q9_18` int(1) DEFAULT NULL,
  `q9_19` int(1) DEFAULT NULL,
  `q9_20` int(2) DEFAULT NULL,
  `q9_21` int(2) DEFAULT NULL,
  `q9_22` int(1) DEFAULT NULL,
  `q9_23` int(1) DEFAULT NULL,
  `q9_23_other_specifz` varchar(100) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_9_hiv_counselling_and_u_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `adt_section_9_hiv_counselling_and_v` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_9_hiv_counselling_and_v_rowid` int(3) NOT NULL,
  `start_time_sect9_data_1` varchar(8) DEFAULT NULL,
  `q9_1` int(1) DEFAULT NULL,
  `q9_2` int(1) DEFAULT NULL,
  `q9_3` int(1) DEFAULT NULL,
  `q9_4` int(1) DEFAULT NULL,
  `q9_5` int(2) DEFAULT NULL,
  `q9_6` int(1) DEFAULT NULL,
  `q9_7` int(1) DEFAULT NULL,
  `q9_8` int(2) DEFAULT NULL,
  `q9_9` int(1) DEFAULT NULL,
  `q9_10a` int(1) DEFAULT NULL,
  `q9_10b_month` int(2) DEFAULT NULL,
  `q9_10b_year` int(4) DEFAULT NULL,
  `q9_11a` int(1) DEFAULT NULL,
  `q9_11b` int(1) DEFAULT NULL,
  `q9_12_number_of_months` int(2) DEFAULT NULL,
  `q9_12_number_of_years` int(2) DEFAULT NULL,
  `q9_13` int(1) DEFAULT NULL,
  `q9_14` int(1) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_9_hiv_counselling_and_v_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adt_section_9_hiv_counselling_and_w` (
  `fifteenandolder_supervisor_ie` int(5) NOT NULL,
  `fifteenandolder_interviewer_ih` int(5) NOT NULL,
  `fifteenandolder_province` int(1) NOT NULL,
  `fifteenandolder_district` int(3) NOT NULL,
  `fifteenandolder_small_area_layev` int(8) NOT NULL,
  `years_and_older_visiting_point` int(3) NOT NULL,
  `years_and_older_household_ques` int(15) NOT NULL,
  `person_no` int(2) NOT NULL,
  `yrs15older_questionnaire_number` int(15) NOT NULL,
  `section_9_hiv_counselling_and_w_rowid` int(3) NOT NULL,
  `hiv_test_filter` int(1) DEFAULT NULL,
  `q9_24a` int(1) DEFAULT NULL,
  `q9_24b` int(1) DEFAULT NULL,
  `q9_24c` int(1) DEFAULT NULL,
  `q9_24d` int(1) DEFAULT NULL,
  `q9_24e` int(1) DEFAULT NULL,
  `q9_24f` int(1) DEFAULT NULL,
  `q9_24g` int(1) DEFAULT NULL,
  `q9_24h` int(1) DEFAULT NULL,
  `q9_24i` int(1) DEFAULT NULL,
  `q9_24j` int(2) DEFAULT NULL,
  `q9_24k` int(2) DEFAULT NULL,
  `q9_24l` int(2) DEFAULT NULL,
  `q9_24_other_specify` varchar(50) DEFAULT NULL,
  `end_time_sect9_data_1` varchar(8) DEFAULT NULL,
  `rowuuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`fifteenandolder_supervisor_ie`,`fifteenandolder_interviewer_ih`,`fifteenandolder_province`,`fifteenandolder_district`,`fifteenandolder_small_area_layev`,`years_and_older_visiting_point`,`years_and_older_household_ques`,`person_no`,`yrs15older_questionnaire_number`,`section_9_hiv_counselling_and_w_rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;





















































